staging:
  adapter: postgresql
  database: horsey_staging

production:
  adapter: postgresql
  database: horsey_production

development:
  adapter: postgresql
  database: horsey_development

test:
  adapter: postgresql
  database: horsey_test